/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ps.bibliotekaklijent.view;

import rs.ac.bg.fon.ps.biblioteka.model.Author;
import rs.ac.bg.fon.ps.biblioteka.model.BookCategory;
import rs.ac.bg.fon.ps.biblioteka.model.Book;
import rs.ac.bg.fon.ps.bibliotekaklijent.validation.ValidationException;
import rs.ac.bg.fon.ps.bibliotekaklijent.validation.Validator;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.biblioteka.bibilotekaklijent.controller.ControllerUI;

/**
 *
 * @author Dragana Stefanovic
 */
public class FrmAddBook extends javax.swing.JDialog {

    private Book book;

    /**
     * Creates new form NewJDialog
     */
    public FrmAddBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Dodavanje knjige");
        book = new Book();
        initComponents();
        FrameCenter.CenteredFrame(this);
        try {
            prepareView();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri inicijalizaciji.", "Greska", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGodinaIzdanja = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbKategorija = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtPisac = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        txtNaz = new javax.swing.JTextField();
        txtKol = new javax.swing.JTextField();
        txtGod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        txtGodinaIzdanja.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova knjiga"));

        jLabel1.setText("Naziv");

        jLabel3.setText("Godina izdanja");

        jLabel6.setText("Kategorija");

        cmbKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Pisac");

        txtPisac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisacActionPerformed(evt);
            }
        });

        jLabel8.setText("Kolicina");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        txtKol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtGodinaIzdanjaLayout = new javax.swing.GroupLayout(txtGodinaIzdanja);
        txtGodinaIzdanja.setLayout(txtGodinaIzdanjaLayout);
        txtGodinaIzdanjaLayout.setHorizontalGroup(
            txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtGodinaIzdanjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbKategorija, 0, 273, Short.MAX_VALUE)
                    .addComponent(txtNaz)
                    .addComponent(txtKol)
                    .addComponent(txtPisac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGod))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtGodinaIzdanjaLayout.setVerticalGroup(
            txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtGodinaIzdanjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtGod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPisac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(txtGodinaIzdanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnDodaj)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGodinaIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtGodinaIzdanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPisacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisacActionPerformed

    private void txtKolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKolActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {

            validateInputs();

            book.setBookName(txtNaz.getText().trim());
            String issueDateStr=txtGod.getText().trim();
            if(issueDateStr.endsWith(".")){
                issueDateStr=issueDateStr.substring(0,issueDateStr.indexOf("."));
            }
            book.setIssueDate(Integer.parseInt(issueDateStr));
            book.setBookCategory(BookCategory.valueOf(cmbKategorija.getSelectedItem().toString()));
            book.setNumberInStock(Integer.parseInt(txtKol.getText().trim()));
            Author a = new Author(null, txtPisac.getText().trim());
            book.setAuthor(a);
            ControllerUI.getInstance().addBook(book);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio novu knjigu!");

        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti knjigu! ", "Greska", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        removeText();

    }//GEN-LAST:event_btnDodajActionPerformed

    public void validateInputs() throws ValidationException {
        Validator.startValidation().validateNotNullOrEmpty(txtNaz.getText(), "Popunite polje za naziv!").throwIfInvalide();
        Validator.startValidation().validateNotNullOrEmpty(txtGod.getText(), "Popunite polje za godinu izdanja!").throwIfInvalide();
        Validator.startValidation().validateNotNullOrEmpty(txtPisac.getText(), "Popunite polje za pisca!").throwIfInvalide();
        Validator.startValidation().validateNotNullOrEmpty(txtKol.getText(), "Popunite polje za kolicinu na stanju!").throwIfInvalide();
        Validator.startValidation().validateValueIsNumber(txtKol.getText().trim(), "Kolicina mora biti broj!").throwIfInvalide();
        Validator.startValidation().validateValueIsNumber(txtGod.getText().trim(), "Godina izdanja mora biti broj!").throwIfInvalide();
        Validator.startValidation().validateNumberNotNegative(txtKol.getText().trim(), "Kolicina ne sme biti negativan broj!").throwIfInvalide();
        Validator.startValidation().validateNumberNotNegative(txtGod.getText().trim(), "Godina ne sme biti negativan broj!").throwIfInvalide();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAddBook dialog = new FrmAddBook(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox cmbKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtGod;
    private javax.swing.JPanel txtGodinaIzdanja;
    private javax.swing.JTextField txtKol;
    private javax.swing.JTextField txtNaz;
    private javax.swing.JTextField txtPisac;
    // End of variables declaration//GEN-END:variables
private void prepareView() throws Exception {
        cmbKategorija.removeAllItems();
        BookCategory[] categories = BookCategory.values();
        for (BookCategory bookCategory : categories) {
            cmbKategorija.addItem(bookCategory);
        }

    }

    private void removeText() {
        txtNaz.setText("");
        txtGod.setText("");
        txtKol.setText("");
        txtPisac.setText("");
    }
}
