/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ps.bibliotekaklijent.view;

import rs.ac.bg.fon.ps.biblioteka.model.Book;
import rs.ac.bg.fon.ps.bibliotekaklijent.view.tableModel.TableModelBook;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import rs.ac.bg.fon.ps.biblioteka.bibilotekaklijent.communication.Communication;
import rs.ac.bg.fon.ps.biblioteka.bibilotekaklijent.controller.ControllerUI;
import rs.ac.bg.fon.ps.biblioteka.communication.Operations;
import rs.ac.bg.fon.ps.biblioteka.communication.Request;
import rs.ac.bg.fon.ps.biblioteka.communication.Response;
import rs.ac.bg.fon.ps.biblioteka.communication.ResponseType;
import rs.ac.bg.fon.ps.biblioteka.model.Author;

/**
 *
 * @author Dragana Stefanovic
 */
public class FrmLoadBook extends javax.swing.JDialog {

    private Book book;
    private JTable table;
    private JComboBox<Author> cmbAuthors;

    public void setTabelaKnjiga(JTable t) {
        table = t;
    }

    public void setCmbAuthors(JComboBox<Author> cmbAuthors) {
        this.cmbAuthors = cmbAuthors;
    }

    /**
     * Creates new form FrmUcitajKnjigu
     */
    public FrmLoadBook(java.awt.Frame parent, boolean modal, Book k) {
        super(parent, modal);
        initComponents();
        book = k;
        setTitle("Informacije o knjizi");

        FrameCenter.CenteredFrame(this);
        try {
            prepareView();
            JOptionPane.showMessageDialog(this, "Sistem je učitao knjigu.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita knjigu.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNaziv = new javax.swing.JLabel();
        txtNazivž = new javax.swing.JTextField();
        lblNaziv1 = new javax.swing.JLabel();
        txtGodinaIzdanja = new javax.swing.JTextField();
        lblNaziv2 = new javax.swing.JLabel();
        txtPisac = new javax.swing.JTextField();
        lblNaziv3 = new javax.swing.JLabel();
        txtKategorija = new javax.swing.JTextField();
        lblNaziv4 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        btnIzbrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o knjizi"));

        jLabel1.setText("ID serije");

        txtId.setEditable(false);

        lblNaziv.setText("Naziv");

        txtNazivž.setEditable(false);
        txtNazivž.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivžActionPerformed(evt);
            }
        });

        lblNaziv1.setText("Godina izdanja");

        txtGodinaIzdanja.setEditable(false);
        txtGodinaIzdanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGodinaIzdanjaActionPerformed(evt);
            }
        });

        lblNaziv2.setText("Pisac");

        txtPisac.setEditable(false);
        txtPisac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisacActionPerformed(evt);
            }
        });

        lblNaziv3.setText("Kategorija");

        txtKategorija.setEditable(false);
        txtKategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKategorijaActionPerformed(evt);
            }
        });

        lblNaziv4.setText("Kolicina");

        txtKolicina.setEditable(false);
        txtKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolicinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtNazivž, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNaziv1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(txtGodinaIzdanja, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNaziv2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(txtPisac, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNaziv3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(txtKategorija, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNaziv4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(txtKolicina, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv)
                    .addComponent(txtNazivž, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv1)
                    .addComponent(txtGodinaIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv2)
                    .addComponent(txtPisac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv3)
                    .addComponent(txtKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv4)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnIzbrisi.setText("Izbriši");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzbrisi)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivžActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivžActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivžActionPerformed

    private void txtGodinaIzdanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGodinaIzdanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGodinaIzdanjaActionPerformed

    private void txtPisacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisacActionPerformed

    private void txtKategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKategorijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategorijaActionPerformed

    private void txtKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKolicinaActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        try {
            ControllerUI.getInstance().deleteBook(book);
            ((TableModelBook) table.getModel()).deleteKnjiga(book);
            refreshComboBox();
            JOptionPane.showMessageDialog(this, "Sistem je obrisao knjigu!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnIzbrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblNaziv1;
    private javax.swing.JLabel lblNaziv2;
    private javax.swing.JLabel lblNaziv3;
    private javax.swing.JLabel lblNaziv4;
    private javax.swing.JTextField txtGodinaIzdanja;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKategorija;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtNazivž;
    private javax.swing.JTextField txtPisac;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        txtId.setText(book.getBookid().toString());
        txtNazivž.setText(book.getBookName());
        txtGodinaIzdanja.setText(book.getIssueDate().toString());
        txtPisac.setText(book.getAuthor().toString());
        txtKolicina.setText(book.getNumberInStock().toString());
        txtKategorija.setText(book.getBookCategory().toString());
    }

    private void refreshComboBox() throws Exception {
        cmbAuthors.removeAllItems();
        List<Author> authors = ControllerUI.getInstance().getAuthors();
        for (Author autor : authors) {
            System.out.println(autor);
            cmbAuthors.addItem(autor);

        }
    }

}
